name: DAJIN
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - biopython
  - muscle
  - mappy
  - numpy
  - parallel
  - pysam
  - python=3.6
  - rtg-tools
  - samtools=1.10
  - vcflib
  - intervaltree=3.*