---
name: 🐞 Bug Report
about: Create a report to help us improve
labels: bug
---

body:
  - type: textarea
    id: description
    attributes:
      label: '📋 Description'
      description: A clear and concise description of the bug.
    validations:
      required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: |
      Optional: A concise description of what you're experiencing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: |
      Optional: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: |
      Optional: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false

  - type: textarea
    id: environment
    attributes:
      label: '🔍 Environment'
      description: |
          Optional: The environment information.
          - **OS**: WSL (Ubuntu 22.04)
          - **DAJIN2**: 0.4.6
      value: |
          - OS:
          - DAJIN2:
      render: markdown
    validations:
      required: false

  - type: textarea
    id: anything_else
    attributes:
      label: Anything else?
      description: |
        Optional: Add any other contexts, links, or screenshots about the bug here.
    validations:
      required: false
