name: 💡 Feature Request
description: Suggest an idea for this project
labels: ['request']

body:
  - type: textarea
    id: description
    attributes:
      label: '📋 Description'
      description: A clear and concise description of the request.
    validations:
      required: true

  - type: input
    id: dajin2_version
    attributes:
      label: '🔖 DAJIN2 Version'
      description: 'Required: Specify the DAJIN2 version you are using. You can find this information in the `DAJIN2 --version` command.'
      placeholder: 'e.g., 0.5.5'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: '🔍 Environment'
      description: |
          Optional: The environment information.
          Example:
          OS: WSL (Ubuntu 22.04)
          Python version: 3.10.15
      value: |
          OS:
          Python version:
      render: markdown
    validations:
      required: false


  - type: textarea
    id: anything_else
    attributes:
      label: '📎 Anything else?'
      description: |
        Optional: Add any other contexts, links, or screenshots about the feature request here.
    validations:
      required: false

