name: ❓ Question
description: Report your question here
labels: ['question']

body:
  - type: textarea
    id: description
    attributes:
      label: '📋 Description'
      description: A clear and concise description of the question.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: '🔍 Environment'
      description: |
          Optional: The environment information.
          Example:
          OS: WSL (Ubuntu 22.04)
          DAJIN2 version: 0.5.5
          Python version: 3.10.15
      value: |
          OS:
          DAJIN2 version:
          Python version:
      render: markdown
    validations:
      required: false


  - type: textarea
    id: anything_else
    attributes:
      label: '📎 Anything else?'
      description: |
        Optional: Add any other contexts, links, or screenshots about the bug here.
    validations:
      required: false
