name: cli-tests

on:
  push:
  schedule:
    - cron: "0 2 * * 1" # The task runs at 2 a.m. every Monday.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: test-env
          channels: bioconda, conda-forge, defaults, anaconda

      - name: Setup conda environment on ubuntu-latest🐧
        if: runner.os == 'Linux'
        run: |
          conda create -y -n env-dajin2 python=${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          conda activate env-dajin2

          # ==========================================
          # Use pip because conda does not support pyproject.toml.
          # ==========================================
          pip install -U pip pytest
          pip install -e .

      ##########################################
      # Execute tests
      ##########################################

      - name: Run tests version
        run: |
          conda activate env-dajin2
          sh tests/test_version.sh
