name: E2E test for Cables2 flox

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12"]
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: test-env
          channels: bioconda, conda-forge, defaults

      - name: Create and activate conda environment
        run: |
          conda create -y -n env-dajin2 python=${{ matrix.python-version }} pip pytest
          conda activate env-dajin2

      - name: Install DAJIN2 and dependencies
        run: |
          pip install -e .

      - name: Download and prepare example dataset
        run: |
          if [ ! -d example_flox ]; then
            curl -LJO https://github.com/akikuno/DAJIN2/raw/main/examples/example_flox.tar.gz
            tar -xf example_flox.tar.gz
          fi

      - name: Execute DAJIN2 batch test
        env:
          PYTHONPATH: src
        run: |
          time DAJIN2 batch --file example_flox/batch.xlsx --threads 4 --debug || exit 1
