name: E2E test for Tyr substitution

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.x"]
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: test-env
          channels: bioconda, conda-forge, defaults

      - name: Create and activate conda environment
        run: |
          conda create -y -n env-dajin2 python=${{ matrix.python-version }} pip pytest
          conda activate env-dajin2

      - name: Install DAJIN2 and dependencies
        run: |
          pip install -e .  # Install DAJIN2 in editable mode

      - name: Download and prepare example dataset
        run: |
          if [ ! -d example_batch ]; then
            curl -LJO https://github.com/akikuno/DAJIN2/raw/main/examples/example_batch.tar.gz
            tar -xf example_batch.tar.gz
          fi

      - name: Modify batch file and execute DAJIN2 batch test
        env:
          PYTHONPATH: src
        run: |
          TODAY=$(date -u "+%Y%m%d")
          sed "s|tyr_c230gt|tyr_c230gt_${TODAY}|" example_batch/batch.csv > /tmp/tmp_batch.csv
          time DAJIN2 batch --file /tmp/tmp_batch.csv --threads 4 --debug || exit 1
