name: Pytest for Ubuntu latest

on:
  push:
  schedule:
    - cron: "0 2 * * 1" # The task runs at 2 a.m. every Monday.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies via pip
        run: |
          python -m pip install --upgrade pip pytest
          python -m pip install -e .

      - name: Install weasyprint on macos-latest🍎
        if: runner.os == 'macOS'
        run: |
            brew install weasyprint

      - name: Test with pytest
        env:
          PYTHONPATH: src
        run: |
          python -m pytest tests/ -p no:warnings -vv
