name: Pytest for darwin-arm64

on:
  push:
  schedule:
    - cron: "0 2 * * 1" # The task runs at 2 a.m. every Monday.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [macos-14]
        python-version: ['3.10']
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies via conda
        run: |
          conda install -y -c conda-forge pytest
          conda install -y -c conda-forge bioconda --file requirements.txt

      - name: Install weasyprint on macos-latest🍎
        if: runner.os == 'macOS'
        run: |
            brew install weasyprint

      - name: Test with pytest
        env:
          PYTHONPATH: src
        run: |
          python -m pytest tests/ -p no:warnings -vv
